#index:
#    path: /
#    controller: App\Controller\DefaultController::index

display_admin:
  path: /dashboard
  controller: App\Controller\UserController::AdminDashboard

display_login:
  path: /login
  controller: App\Controller\UserController::login

display_sign_up:
  path: /sign_up
  controller: App\Controller\UserController::sign_up

display_profile:
  path: /profile/{id}
  controller: App\Controller\UserController::profile

delete_user:
  path: /delete_User/{id}
  controller: App\Controller\UserController::deleteUser

go_to_logout:
  path: /logout
  controller: App\Controller\UserController::logout

display_home:
  path: /home
  controller: App\Controller\UserController::home

display_work:
  path: /work_in_progress
  controller: App\Controller\UserController::work

verif_user:
  path: /verif/{token}
  controller: App\Controller\UserController::VerifyUser

display_resend_verif:
  path: /resend_verif/{id}
  controller: App\Controller\UserController::resendVerif

display_forgetPassword:
  path: /forgetPassword
  controller: App\Controller\UserController::forgottenPassword

resetPass:
  path: /resetPassword/{token}
  controller: App\Controller\UserController::resetPassword

2fa:
  path: /2fa/{id}
  controller: App\Controller\UserController::FA

  #index:
#    path: /
#    controller: App\Controller\DefaultController::index
display_materials:
  path: /materials
  controller: App\Controller\MaterialsController::index
display_addmaterials:
  path: /addmaterials/{id}
  controller: App\Controller\MaterialsController::addmaterials
display_affichermaterials:
  path: /affichermaterials
  controller: App\Controller\MaterialsController::affichermaterials
display_editmaterials:
  path: /editmaterials/{id}
  controller: App\Controller\MaterialsController::editmaterials
display_deletematerials:
  path: /deletematerials/{id}
  controller: App\Controller\MaterialsController::deletematerials
display_adddepot:
  path: /adddepot
  controller: App\Controller\DepotController::adddepot
display_afficherdepot:
  path: /afficherdepot
  controller: App\Controller\DepotController::afficherdepot
display_editdepot:
  path: /editdepot/{id}
  controller: App\Controller\DepotController::editdepot
display_deletedepot:
  path: /deletedepot/{id}
  controller: App\Controller\DepotController::deletedepot
depot_pdf_generate:
    path: '/generatePdf/{id}'
    controller: App\Controller\DepotController::generatePdf
app_map:
    path: '/map'
    controller: App\Controller\DepotController::map
search_depot:
    path: '/searchdepot'
    controller: App\Controller\DepotController::searchdepot


  
    
