#index:
#    path: /
#    controller: App\Controller\DefaultController::index
display_materials:
  path: /materials
  controller: App\Controller\MaterialsController::index
display_addmaterials:
  path: /addmaterials
  controller: App\Controller\MaterialsController::addmaterials
display_affichermaterials:
  path: /affichermaterials
  controller: App\Controller\MaterialsController::affichermaterials
display_editmaterials:
  path: /editmaterials/{id}
  controller: App\Controller\MaterialsController::editmaterials
display_deletematerials:
  path: /deletematerials/{id}
  controller: App\Controller\MaterialsController::deletematerials
display_home:
  path: /home
  controller: App\Controller\DepotController::home
display_adddepot:
  path: /adddepot
  controller: App\Controller\DepotController::adddepot
display_afficherdepot:
  path: /afficherdepot
  controller: App\Controller\DepotController::afficherdepot
display_editdepot:
  path: /editdepot/{id}
  controller: App\Controller\DepotController::editdepot
display_deletedepot:
  path: /deletedepot/{id}
  controller: App\Controller\DepotController::deletedepot


  